from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

from fastapi.testclient import TestClient

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.api import server as api_server


HTML_MOJIBAKE_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff\ufffd]")
HTML_PLACEHOLDER_RE = re.compile(r"\?{2,}")

REQUIRED_UI_MARKERS: dict[str, str] = {
    "analysis form": 'id="analysisForm"',
    "ticker input": 'id="ticker"',
    "ticker search picker": 'id="tickerSearchOpen"',
    "question textarea": 'id="question"',
    "language toggle": 'id="languageToggle"',
    "language toggle korean": 'data-language="ko"',
    "language toggle english": 'data-language="en"',
    "result view": 'id="resultView"',
    "home dashboard": 'id="emptyState"',
    "dashboard tabs": 'id="homeDashboardTabs"',
    "dashboard decision context strip": 'id="dashboardContextStrip"',
    "global quality summary": 'id="globalQualitySummary"',
    "global quality observations": 'data-summary-field="observations"',
    "global quality missing": 'data-summary-field="missing"',
    "global quality ai snapshot": 'data-summary-field="ai-snapshot"',
    "global quality context": 'id="qualityContextSummary"',
    "quality artifact paths": 'id="qualityArtifactPaths"',
    "quality evaluation detail folding": 'class="quality-detail-list quality-eval-detail"',
    "global quality context source": 'data-quality-detail="source"',
    "global quality context cache": 'data-quality-detail="cache"',
    "global quality context range support": 'data-quality-detail="range-support"',
    "macro dashboard range controls": 'id="macroRangeControls"',
    "macro explorer range controls": 'aria-label="Macro Explorer range controls"',
    "dashboard range macro placement": 'dashboard-range-controls--macro-search',
    "macro dashboard range select": 'id="macroRangeSelect"',
    "macro dashboard range start": 'id="macroRangeStart"',
    "macro dashboard range end": 'id="macroRangeEnd"',
    "quantamental ai model selector": 'id="quantamentalAiModel"',
    "quantamental ai model status": 'id="quantamentalAiModelStatus"',
    "quantamental ai model contract": 'data-testid="quantamental-ai-model-control"',
    "market dashboard tab": 'id="marketDashboardTab"',
    "market dashboard tab testid": 'data-testid="market-dashboard-tab"',
    "market tape primary tier": '<section class="home-card market-overview-card market-surface" data-panel-tier="primary">',
    "market signal primary tier": '<section class="home-card market-signals-card market-surface" data-panel-tier="primary">',
    "market chart primary tier": '<section class="home-card home-chart-card market-surface" data-panel-tier="primary">',
    "market heatmap primary tier": '<section class="home-card home-heatmap-card market-surface" data-panel-tier="primary">',
    "market news details tier": '<section class="home-card home-news-card market-surface" data-panel-tier="details">',
    "macro dashboard tab": 'id="macroDashboardTab"',
    "macro dashboard tab testid": 'data-testid="macro-dashboard-tab"',
    "risk dashboard tab": 'id="riskDashboardTab"',
    "risk dashboard tab testid": 'data-testid="risk-dashboard-tab"',
    "auto trading tab": 'id="autoTradingTab"',
    "auto trading tab testid": 'data-testid="auto-trading-tab"',
    "auto trading workbench": 'data-testid="auto-trading-workbench"',
    "auto trading asset input": 'id="autoTradingTicker"',
    "auto trading strategy select": 'id="autoTradingStrategySelect"',
    "auto trading code editor": 'id="autoTradingCode"',
    "auto trading llm parameter tuning": 'data-testid="auto-trading-llm-parameter-tuning"',
    "auto trading parameter objective": 'id="autoTradingParamObjective"',
    "auto trading parameter search space": 'id="autoTradingParamSearchSpace"',
    "auto trading parameter surface": 'id="autoTradingParamSurface"',
    "auto trading signal chart surface": 'id="autoTradingChartSurface"',
    "auto trading backtest action": 'data-testid="auto-trading-backtest"',
    "auto trading optimize action": 'data-testid="auto-trading-optimize"',
    "auto trading control plane": 'data-testid="auto-trading-control-plane"',
    "auto trading surface": 'auto-trading-surface',
    "risk workbench panel": 'id="riskWorkbenchPanel"',
    "risk executive strip": 'id="riskExecutiveStrip"',
    "risk decision brief": 'id="riskDecisionBrief"',
    "risk driver waterfall": 'id="riskDriverWaterfall"',
    "risk company table": 'id="riskCompanyTable"',
    "risk macro pressure panel": 'id="riskMacroPressurePanel"',
    "risk transmission matrix": 'id="riskTransmissionMatrix"',
    "risk scenario matrix": 'id="riskScenarioMatrix"',
    "risk evidence drawer": 'id="riskEvidenceDrawer"',
    "risk run action": 'data-testid="risk-run"',
    "quant lab tab": 'id="quantLabTab"',
    "quant lab tab testid": 'data-testid="quant-lab-tab"',
    "quantamental tab": 'id="quantamentalTab"',
    "quantamental tab testid": 'data-testid="quantamental-tab"',
    "ml forecast tab": 'id="mlForecastTab"',
    "ml forecast tab testid": 'data-testid="ml-forecast-tab"',
    "ai portfolio tab": 'id="aiPortfolioTab"',
    "ai portfolio tab testid": 'data-testid="ai-portfolio-tab"',
    "run history": 'id="historyList"',
    "market overview meta": 'id="marketOverviewMeta"',
    "market tape": 'id="marketTapeSurface"',
    "market signals": 'id="marketSignalSurface"',
    "cross asset symbols": 'id="crossAssetSymbols"',
    "cross asset analysis": 'id="crossAssetAnalysisSurface"',
    "cross asset run": 'data-testid="cross-asset-run"',
    "cross asset pair default": 'value="SPY, GLD"',
    "cross asset decision memo copy": "데이터 분석 메모",
    "cross asset engineering diagnostics": "베타 헤지·z-score 진단",
    "home news": 'id="homeNewsList"',
    "focused news": 'id="homeNewsFocusedList"',
    "news search run": 'data-testid="market-news-search-run"',
    "tradingview chart": 'id="tvOverviewWidget"',
    "market chart source": 'id="tvChartSource"',
    "tradingview chart symbol": 'id="tvChartSymbol"',
    "tradingview chart interval": 'id="tvChartInterval"',
    "tradingview chart compare": 'id="tvChartCompare"',
    "tradingview chart apply": 'data-testid="tradingview-chart-apply"',
    "intraday heatmap": 'id="homeHeatmap"',
    "intraday heatmap refresh": 'id="homeHeatmapRefresh"',
    "intraday heatmap refresh testid": 'data-testid="market-heatmap-refresh"',
    "quality data health": 'id="qualityDataHealth"',
    "quality data refresh": 'id="qualityRefresh"',
    "quality all-data refresh": 'id="dataAutoRefreshRun"',
    "quality all-data refresh status": 'id="dataAutoRefreshStatus"',
    "quality ops quant stack": 'id="qualityOpsQuant"',
    "quality ops forecast stack": 'id="qualityOpsForecast"',
    "quality ops quantamental stack": 'id="qualityOpsQuantamental"',
    "quality ops ai portfolio stack": 'id="qualityOpsAiPortfolio"',
    "macro surface": 'id="macroSurface"',
    "macro refresh": 'id="macroRefresh"',
    "macro refresh testid": 'data-testid="macro-refresh"',
    "macro brief generate": 'id="macroBriefGenerate"',
    "macro brief generate testid": 'data-testid="macro-brief-generate"',
    "macro report export": 'id="macroReportExport"',
    "macro report export testid": 'data-testid="macro-report-export"',
    "macro load status": 'id="macroLoadStatus"',
    "macro overview": 'id="macroOverviewSurface"',
    "macro coverage": 'id="macroCoverageSurface"',
    "macro provider health": 'id="macroProviderHealthSurface"',
    "macro quality panel section": 'id="qualityMacroData"',
    "macro diagnostics quality placement": 'class="quality-diagnostic-grid"',
    "macro data quality quality placement": 'id="macroDataQualitySurface" class="decision-surface compact-surface quality-diagnostic-surface"',
    "macro series search input": 'id="macroSeriesSearchInput"',
    "macro series search action": 'id="macroSeriesSearchRun"',
    "macro series search action testid": 'data-testid="macro-series-search-run"',
    "macro series search results": 'id="macroSeriesSearchResults"',
    "macro series detail": 'id="macroSeriesDetailSurface"',
    "macro provider filter": 'id="macroProviderFilter"',
    "macro category filter": 'id="macroCategoryFilter"',
    "macro compare": 'id="macroCompareSurface"',
    "macro indicators": 'id="macroIndicatorTable"',
    "macro chart surface": 'id="macroChartSurface"',
    "macro interest rates": 'id="macroInterestRatesSurface"',
    "macro inflation": 'id="macroInflationSurface"',
    "macro growth labor": 'id="macroGrowthLaborSurface"',
    "macro housing consumer": 'id="macroHousingConsumerSurface"',
    "macro yield curve": 'id="macroYieldCurveSurface"',
    "macro liquidity credit": 'id="macroLiquidityCreditSurface"',
    "macro financial conditions": 'id="macroFinancialConditionsSurface"',
    "macro fx dollar": 'id="macroFxDollarSurface"',
    "macro commodities": 'id="macroCommoditiesSurface"',
    "macro regime": 'id="macroRegimeSurface"',
    "macro asset impact": 'id="macroAssetImpactSurface"',
    "macro scenario": 'id="macroScenarioSurface"',
    "macro scenario action": 'data-action="macro-scenario"',
    "macro research preview": 'id="macroResearchPreviewSurface"',
    "macro research ticker": 'id="macroResearchTicker"',
    "macro research preview action": 'id="macroResearchPreviewRun"',
    "macro research preview action testid": 'data-testid="macro-research-preview-run"',
    "macro research preview result": 'id="macroResearchPreviewResult"',
    "macro portfolio hints": 'id="macroPortfolioHintsSurface"',
    "macro brief": 'id="macroBriefSurface"',
    "macro data quality": 'id="macroDataQualitySurface"',
    "asset detail": 'id="assetDetailSurface"',
    "asset detail ticker picker": 'id="assetDetailTickerOpen"',
    "asset detail range": 'id="assetDetailRange"',
    "asset detail start date": 'id="assetDetailStartDate"',
    "asset detail end date": 'id="assetDetailEndDate"',
    "asset detail view": 'id="assetDetailView"',
    "asset detail benchmark": 'id="assetDetailBenchmark"',
    "asset detail benchmark picker": 'id="assetDetailBenchmarkOpen"',
    "asset detail benchmark compare": 'id="assetDetailBenchmarkCompare"',
    "quant feature preview": 'id="quantFeatureSurface"',
    "quant feature preview action": 'id="quantFeatureRun"',
    "quant feature preview action testid": 'data-testid="quant-feature-run"',
    "quant signal matrix": 'id="quantSignalSurface"',
    "quant signal matrix action": 'id="quantSignalRun"',
    "quant signal matrix action testid": 'data-testid="quant-signal-run"',
    "python strategy run": 'id="pythonStrategyRun"',
    "python strategy run testid": 'data-testid="python-strategy-run"',
    "python strategy lab": 'data-testid="python-strategy-lab"',
    "python strategy code": 'id="pythonStrategyCode"',
    "python strategy result": 'data-testid="python-strategy-result-surface"',
    "backtest": 'id="backtestSurface"',
    "backtest run": 'id="backtestRun"',
    "backtest run testid": 'data-testid="quant-backtest-run"',
    "backtest universe picker": 'id="backtestUniverseOpen"',
    "backtest universe chips": 'id="backtestUniverseChips"',
    "backtest strategy registry": 'id="backtestStrategyRegistry"',
    "backtest risk adjusted momentum option": 'value="risk_adjusted_momentum"',
    "backtest benchmark": 'id="backtestBenchmark"',
    "backtest benchmark picker": 'id="backtestBenchmarkOpen"',
    "backtest benchmark compare": 'id="backtestBenchmarkCompare"',
    "strategy research lab": 'data-testid="strategy-research-lab"',
    "strategy research auto tab": 'class="home-card strategy-research-card auto-trading-surface"',
    "strategy research optimize": 'data-testid="strategy-research-optimize"',
    "strategy research diagnostics": 'id="strategyResearchDiagnosticsSurface"',
    "strategy research hypotheses": 'id="strategyResearchHypothesisSurface"',
    "strategy research validation": 'id="strategyResearchValidationSurface"',
    "symbol picker modal": 'id="symbolPickerModal"',
    "symbol picker title": 'id="symbolPickerTitle"',
    "symbol picker description": 'id="symbolPickerDescription"',
    "symbol picker summary": 'id="symbolPickerSummary"',
    "symbol picker add filtered": 'id="symbolPickerAddFiltered"',
    "symbol picker remove filtered": 'id="symbolPickerRemoveFiltered"',
    "freshness profile": 'id="backtestFreshnessProfile"',
    "strict freshness toggle": 'id="backtestRequireFresh"',
    "research score toggle": 'id="backtestUseResearchScore"',
    "quant run history": 'id="quantRunHistorySurface"',
    "quant run history refresh": 'id="quantRunHistoryRefresh"',
    "quant run history refresh testid": 'data-testid="quant-run-history-refresh"',
    "quant export storage report": 'id="quantExportStorageReport"',
    "quant export storage report testid": 'data-testid="quant-export-storage-report"',
    "quant cross-run cleanup preview": 'id="quantCrossRunCleanupPreview"',
    "quant cross-run cleanup preview testid": 'data-testid="quant-cross-run-cleanup-preview"',
    "quant compact report action": 'title="내보내기 저장소 리포트">리포트</button>',
    "quant compact cleanup action": 'title="실행 간 내보내기 정리 미리보기">정리</button>',
    "quant compact refresh action": 'title="실행 이력 새로고침">갱신</button>',
    "quantamental surface": 'id="quantamentalSurface"',
    "quantamental ticker": 'id="quantamentalTicker"',
    "quantamental ticker picker": 'id="quantamentalTickerOpen"',
    "quantamental market": 'id="quantamentalMarket"',
    "quantamental period": 'id="quantamentalPeriod"',
    "quantamental years": 'id="quantamentalYears"',
    "quantamental lookback": 'id="quantamentalLookback"',
    "quantamental style": 'id="quantamentalStyle"',
    "quantamental analyze": 'id="quantamentalAnalyze"',
    "quantamental analyze testid": 'data-testid="quantamental-analyze"',
    "quantamental company": 'id="quantamentalCompanySurface"',
    "quantamental signal": 'id="quantamentalSignalSurface"',
    "quantamental score": 'id="quantamentalScoreSurface"',
    "quantamental factors": 'id="quantamentalFactorSurface"',
    "quantamental main": 'id="quantamentalMainSurface"',
    "quantamental ai report": 'id="quantamentalAiRefresh"',
    "quantamental ai report testid": 'data-testid="quantamental-ai-report"',
    "quantamental data quality": 'id="quantamentalDataQualitySurface"',
    "ml forecast surface": 'id="mlForecastSurface"',
    "ml forecast ticker": 'id="forecastTicker"',
    "ml forecast ticker picker": 'id="forecastTickerOpen"',
    "ml forecast benchmark": 'id="forecastBenchmark"',
    "ml forecast benchmark picker": 'id="forecastBenchmarkOpen"',
    "ml forecast horizon": 'id="forecastHorizon"',
    "ml forecast target": 'id="forecastTargetType"',
    "ml forecast model": 'id="forecastModel"',
    "ml forecast validation": 'id="forecastValidation"',
    "ml forecast preview action": 'id="forecastPreviewDataset"',
    "ml forecast preview testid": 'data-testid="ml-forecast-preview"',
    "ml forecast hydrate action": 'id="forecastHydrateDataset"',
    "ml forecast hydrate testid": 'data-testid="ml-forecast-hydrate"',
    "ml forecast feature action": 'id="forecastBuildFeatures"',
    "ml forecast feature testid": 'data-testid="ml-forecast-features"',
    "ml forecast train action": 'id="forecastRunTrain"',
    "ml forecast train testid": 'data-testid="ml-forecast-train"',
    "ml forecast universe preset": 'id="forecastUniversePreset"',
    "ml forecast universe tickers": 'id="forecastUniverseTickers"',
    "ml forecast universe picker": 'id="forecastUniverseOpen"',
    "ml forecast universe chips": 'id="forecastUniverseChips"',
    "ml forecast universe max assets": 'id="forecastUniverseMaxAssets"',
    "ml forecast universe rank metric": 'id="forecastUniverseRankMetric"',
    "ml forecast universe action": 'id="forecastRunUniverse"',
    "ml forecast universe testid": 'data-testid="ml-forecast-universe-run"',
    "ml forecast universe surface": 'id="forecastUniverseSurface"',
    "ml forecast ai action": 'id="forecastGenerateAi"',
    "ml forecast ai testid": 'data-testid="ml-forecast-ai"',
    "ml forecast provider ai action": 'id="forecastGenerateProviderAi"',
    "ml forecast provider ai testid": 'data-testid="ml-forecast-provider-ai"',
    "ml forecast dataset": 'id="forecastDatasetSurface"',
    "ml forecast features": 'id="forecastFeatureSurface"',
    "ml forecast leakage": 'id="forecastLeakageSurface"',
    "ml forecast result": 'id="forecastResultSurface"',
    "quant model profile card": 'class="home-card model-profile-card quant-surface"',
    "quant model profile dry run": 'id="quantModelProfileDryRun"',
    "quant model lab run": 'data-testid="quant-model-lab-run"',
    "ml forecast universe primary tier": '<section class="home-card forecast-card forecast-universe-card forecast-surface model-lab-surface quant-surface" data-panel-tier="primary">',
    "ml forecast signal primary tier": '<section class="home-card forecast-card forecast-surface model-lab-surface quant-surface forecast-signal-card" data-panel-tier="primary">',
    "ml forecast signal": 'id="forecastSignalSurface"',
    "ml forecast signal quality": 'id="forecastSignalQualitySurface"',
    "ml forecast visualization primary tier": '<section class="home-card forecast-card forecast-viz-card forecast-surface model-lab-surface quant-surface" data-panel-tier="primary">',
    "ml forecast visualization": 'id="forecastVizSurface"',
    "ml forecast visualization guided placeholder": "축 설명과 해석이 포함된 예측 품질",
    "ml forecast backtest": 'id="forecastBacktestSurface"',
    "ml forecast evaluation": 'id="forecastEvaluationSurface"',
    "ml forecast explain": 'id="forecastExplainSurface"',
    "ml forecast ai surface": 'id="forecastAiSurface"',
    "ml forecast ai provider check": 'id="forecastAiProviderCheck"',
    "ml forecast ai provider surface": 'id="forecastAiProviderSurface"',
    "ml forecast drift refresh": 'id="forecastDriftRefresh"',
    "ml forecast drift surface": 'id="forecastDriftSurface"',
    "ml forecast model comparison refresh": 'id="forecastModelComparisonRefresh"',
    "ml forecast model comparison surface": 'id="forecastModelComparisonSurface"',
    "ml forecast history": 'id="forecastHistorySurface"',
    "ml forecast registry": 'id="forecastRegistrySurface"',
    "portfolio optimizer": 'id="portfolioSurface"',
    "portfolio universe picker": 'id="portfolioUniverseOpen"',
    "portfolio universe chips": 'id="portfolioUniverseChips"',
    "portfolio sync backtest": 'id="portfolioSyncBacktest"',
    "portfolio sync backtest testid": 'data-testid="portfolio-sync-backtest"',
    "portfolio optimize action": 'id="portfolioOptimize"',
    "portfolio optimize action testid": 'data-testid="portfolio-optimize"',
    "portfolio benchmark": 'id="portfolioBenchmark"',
    "portfolio benchmark picker": 'id="portfolioBenchmarkOpen"',
    "portfolio covariance method": 'id="portfolioCovarianceMethod"',
    "ai portfolio surface": 'id="aiPortfolioSurface"',
    "ai portfolio investment types": 'id="aiPortfolioInvestmentTypes"',
    "ai portfolio universe preset": 'id="aiPortfolioUniverse"',
    "ai portfolio custom universe": 'id="aiPortfolioCustomUniverse"',
    "ai portfolio custom universe picker": 'id="aiPortfolioCustomUniverseOpen"',
    "ai portfolio custom universe chips": 'id="aiPortfolioCustomUniverseChips"',
    "ai portfolio universe status": 'id="aiPortfolioUniverseStatus"',
    "ai portfolio ops": 'id="aiPortfolioOpsSurface"',
    "ai portfolio ops refresh": 'id="aiPortfolioOpsRefresh"',
    "quantamental composite": 'id="quantamentalScoreSurface"',
    "quantamental factor": 'id="quantamentalFactorSurface"',
    "quantamental ai action": 'id="quantamentalAiRefresh"',
    "quantamental ai testid": 'data-testid="quantamental-ai-report"',
    "quantamental quality": 'id="quantamentalDataQualitySurface"',
    "quantamental compare tickers": 'id="quantamentalCompareTickers"',
    "quantamental compare action": 'id="quantamentalCompareRun"',
    "quantamental compare testid": 'data-testid="quantamental-compare-run"',
    "quantamental compare surface": 'id="quantamentalCompareSurface"',
    "quantamental expand peers": 'id="quantamentalExpandPeers"',
    "quantamental peer limit": 'id="quantamentalPeerLimit"',
    "quantamental compare watchlist name": 'id="quantamentalWatchlistName"',
    "quantamental compare watchlist select": 'id="quantamentalWatchlistSelect"',
    "quantamental compare watchlist save": 'data-testid="quantamental-watchlist-save"',
    "quantamental compare watchlist load": 'data-testid="quantamental-watchlist-load"',
    "quantamental compare csv": 'data-testid="quantamental-compare-csv"',
    "quantamental screen action": 'id="quantamentalScreenRun"',
    "quantamental screen action testid": 'data-testid="quantamental-screen-run"',
    "quantamental screen status": 'id="quantamentalScreenStatus"',
    "quantamental screen surface": 'id="quantamentalScreenSurface"',
    "quantamental score screen threshold": 'id="quantamentalScoreThreshold"',
    "quantamental score screen metric": 'id="quantamentalScoreMetric"',
    "quantamental score screen limit": 'id="quantamentalScoreScreenLimit"',
    "quantamental score screen action": 'id="quantamentalScoreScreenRun"',
    "quantamental score screen action testid": 'data-testid="quantamental-score-screen-run"',
    "quantamental score screen status": 'id="quantamentalScoreScreenStatus"',
    "quantamental score screen surface": 'id="quantamentalScoreScreenSurface"',
    "market ui module": 'modules/market-ui.js?v=20260521-market-signals-v1',
    "macro ui module": 'modules/macro-ui.js?v=20260521-market-signals-v1',
    "forecast ui module": 'modules/forecast-ui.js?v=20260521-market-signals-v1',
    "quant ui module": 'modules/quant-ui.js?v=20260521-market-signals-v1',
    "ai portfolio ui module": 'modules/ai-portfolio-ui.js?v=20260520-ai-portfolio-ops-v1',
    "quantamental ui module": 'modules/quantamental-ui.js?v=20260521-quantamental-decision-v23',
    "ai portfolio operation hydrate": 'id="aiPortfolioHydrateData"',
    "ai portfolio operation retry": 'id="aiPortfolioRetryMissing"',
    "ai portfolio snapshot job": 'id="aiPortfolioSnapshotJob"',
    "ai portfolio sec refresh": 'id="aiPortfolioSecRefresh"',
    "ai portfolio policy list": 'id="aiPortfolioPolicyListSurface"',
    "ai portfolio recommendation diff": 'id="aiPortfolioRecommendationDiffSurface"',
    "ai portfolio operations history": 'id="aiPortfolioOperationsSurface"',
    "ai portfolio policy form": 'id="aiPortfolioPolicyForm"',
    "ai portfolio benchmark picker": 'id="aiPortfolioBenchmarkOpen"',
    "ai portfolio generate": 'id="aiPortfolioGenerate"',
    "ai portfolio recommendation": 'id="aiPortfolioRecommendationSurface"',
    "ai portfolio performance": 'id="aiPortfolioPerformanceSurface"',
    "ai portfolio compliance": 'id="aiPortfolioComplianceSurface"',
    "ai portfolio rebalance": 'id="aiPortfolioRebalanceSurface"',
    "ai portfolio reports": 'id="aiPortfolioReportsSurface"',
    "ai portfolio history": 'id="aiPortfolioHistorySurface"',
}

REQUIRED_APP_JS_MARKERS: dict[str, str] = {
    "all default panel views": "DEFAULT_DASHBOARD_PANEL_VIEWS",
    "all default panel version": "DASHBOARD_PANEL_LAYOUT_VERSION",
    "market panel filter visible": "els.dashboardViewControls.hidden = false",
    "market panel view applies": "els.homeSurfaceGrid.dataset.panelView = normalized",
    "macro range storage": "fingpt.dashboardRange.v1",
    "macro range setter": "function setGlobalRange",
    "macro range date order guard": "function normalizeCustomGlobalDateOrder",
    "macro range validation copy": "function globalRangeValidationMessage",
    "macro range support summary": "Macro Explorer 검색과 매크로 차트에만 적용됩니다",
    "macro range placement guard": "function ensureMacroRangeControlPlacement",
    "macro range request options": "function macroRangeRequestOptions",
    "macro range filtered observations": "function macroRangeFilteredObservations",
    "global quality summary": "function updateGlobalQualitySummary",
    "global quality range pending": "function markGlobalQualityRangePending",
    "global quality context summary": "function renderGlobalQualityContextSummary",
    "global quality missing summary": "function displayMissingSummary",
    "global quality ai basis label": "AI 기준:",
    "compact internal id renderer": "function compactIdentifier",
    "compact internal id cell renderer": "function compactIdentifierCell",
    "dashboard decision cards api": "dashboardDecisionCards",
    "dashboard decision cards loader": "function loadDashboardDecisionCards",
    "dashboard intraday chart api": "dashboardIntraday",
    "internal chart payload loader": "function fetchInternalChartPayload",
    "internal chart intraday intervals": "TV_INTERNAL_INTRADAY_INTERVALS",
    "cross asset decision memo": "function renderCrossAssetDecisionMemo",
    "cross asset decision grade label": "function crossAssetDecisionGradeLabel",
    "cross asset engineering panel": "function renderCrossAssetEngineeringPanel",
    "cross asset engineering status label": "function crossAssetEngineeringStatusLabel",
    "quant run history compact summary": "function renderQuantRunHistorySummary",
    "quant run history compact data cell": "function renderQuantHistoryDataCell",
    "quant run history compact compare copy": "비교 0/2",
    "strategy research loader": "function loadStrategyResearchLab",
    "strategy research optimizer": "async function runStrategyResearchOptimize",
    "strategy research validator": "async function runStrategyResearchValidation",
    "python strategy api": "quantPythonStrategyRun",
    "python strategy runner": "async function runPythonStrategyLab",
    "python strategy chart": "function renderPythonStrategyChart",
    "python strategy indicator panel": "function renderPythonStrategyIndicatorPanel",
    "python strategy trade paths": "function renderPythonStrategyTradePaths",
    "python strategy explanation": "function renderPythonStrategyExplanation",
    "python strategy optimization visual": "function renderPythonStrategyOptimizationVisual",
    "python strategy robustness validation": "function renderPythonStrategyRobustness",
    "python strategy manifest": "function renderPythonStrategyParameterManifest",
    "quant factor diagnostic panel": "function renderQuantFeatureDiagnosticPanel",
    "quant backtest signal matrix panel": "function renderBacktestSignalMatrixPanel",
    "quant backtest engineering panel": "function renderBacktestEngineeringPanel",
    "quant backtest monthly heatmap": "function renderBacktestReturnHeatmap",
    "quant rebalance allocation map": "function renderRebalanceAllocationMap",
    "portfolio engineering panel": "function renderPortfolioEngineeringPanel",
    "portfolio risk budget map": "function renderPortfolioAllocationMap",
    "portfolio stress panel": "function renderPortfolioStressPanel",
    "portfolio correlation heatmap": "function renderCorrelationHeatmap",
    "macro default series detail loader": "function loadMacroDefaultSeriesDetail",
    "macro dashboard api": "macroDashboard",
    "macro provider health api": "macroProviderHealth",
    "macro scenario api": "macroScenario",
    "macro research context api": "macroResearchContext",
    "macro timeout fetch": "macroFetchJsonWithTimeout",
    "macro load status renderer": "function renderMacroLoadStatus",
    "macro panel failure renderer": "function renderMacroPanelFailure",
    "macro action pane starter renderer": "function renderMacroActionPaneStarters",
    "macro refresh preserves dashboard": "\uae30\uc874 \ub300\uc2dc\ubcf4\ub4dc \ud654\uba74\uc744 \uc720\uc9c0",
    "macro provider health renderer": "function renderMacroProviderHealth",
    "macro scenario runner": "function runMacroScenario",
    "macro research preview runner": "function runMacroResearchPreview",
    "risk api": "risk: {",
    "risk loader": "function loadRiskWorkbench",
    "risk renderer": "function renderRiskWorkbench",
    "risk decision brief renderer": "function renderRiskDecisionBrief",
    "risk driver visual renderer": "risk-driver-visual",
    "risk transmission flow renderer": "risk-transmission-flow",
    "risk scenario heatmap renderer": "risk-scenario-heatmap",
    "risk visual control plane renderer": "risk-visual-control-plane",
    "risk readiness radar renderer": "risk-readiness-radar",
    "risk readiness radar helper": "function renderRiskReadinessRadar",
    "risk workflow lane renderer": "risk-workflow-lane",
    "risk causal path map renderer": "risk-causal-path-map",
    "risk causal path map helper": "function renderRiskCausalPathMap",
    "risk coverage topology renderer": "risk-coverage-topology",
    "risk coverage topology helper": "function renderRiskCoverageTopology",
    "risk pressure stack renderer": "risk-pressure-stack",
    "risk pressure stack helper": "function renderRiskPressureStack",
    "risk pressure stack data helper": "function buildRiskPressureStackItems",
    "risk visual rail helper": "function renderRiskVisualRail",
    "risk aggregate status helper": "function riskAggregateStatus",
    "risk evidence trace map renderer": "risk-evidence-trace-map",
    "risk service gate rail renderer": "risk-service-gate-rail",
    "risk decision path renderer": "risk-decision-path",
    "risk decision path payload": "decision_path",
    "risk decision compass renderer": "risk-decision-compass",
    "risk decision compass payload": "decision_compass",
    "risk decision compass step renderer": "risk-compass-step",
    "risk decision quality renderer": "risk-decision-quality",
    "risk decision quality payload": "decision_quality",
    "risk evidence coverage renderer": "risk-evidence-coverage",
    "risk evidence coverage detail": "risk-evidence-coverage-detail",
    "risk evidence coverage payload": "evidence_coverage",
    "risk compatibility matrix renderer": "risk-compatibility-matrix",
    "risk compatibility matrix detail": "risk-compatibility-detail",
    "risk compatibility matrix payload": "compatibility_matrix",
    "risk ai output controls renderer": "risk-ai-output-controls",
    "risk ai output detail": "risk-ai-output-detail",
    "risk ai output controls payload": "ai_output_controls",
    "risk action checklist renderer": "risk-action-checklist",
    "risk action checklist status": "function riskActionStatusClass",
    "risk action checklist payload": "action_checklist",
    "risk monitoring trigger renderer": "risk-monitoring-triggers",
    "risk monitoring trigger payload": "monitoring_triggers",
    "risk priority map renderer": "risk-priority-map",
    "risk priority map payload": "priority_map",
    "risk confidence factor renderer": "risk-confidence-ladder",
    "risk confidence factor payload": "confidence_factors",
    "risk handoff queue renderer": "risk-handoff-queue",
    "risk handoff queue payload": "handoff_queue",
    "risk ML validation renderer": "risk-ml-validation-tests",
    "risk ML validation payload": "ml_validation_tests",
    "risk ML validation prefill payload": "forecast_prefill",
    "risk ML validation launch link": "launch_href",
    "risk forecast validation plan renderer": "risk-forecast-validation-plan",
    "risk forecast validation plan detail": "risk-forecast-validation-detail",
    "risk forecast validation plan payload": "forecast_validation_plan",
    "risk forecast prefill handler": "function applyForecastPrefillFromLocation",
    "risk forecast handoff state": "forecastRiskHandoff",
    "risk forecast handoff renderer": "function renderForecastRiskHandoffNotice",
    "risk forecast source context": "source_context",
    "risk forecast test type param": "riskTestType",
    "risk forecast prefill card": "risk-forecast-prefill-card",
    "risk service readiness renderer": "risk-service-readiness",
    "risk service readiness status": "function riskReadinessStatusClass",
    "risk service readiness payload": "service_readiness",
    "risk release packet renderer": "risk-release-packet",
    "risk release packet payload": "release_packet",
    "risk release packet checks": "deployment_checks",
    "risk input receipt renderer": "risk-input-receipt",
    "risk input receipt payload": "input_receipt",
    "risk run lineage renderer": "risk-run-lineage",
    "risk run lineage payload": "run_lineage",
    "risk portfolio position parser": "function riskPortfolioPositions",
    "risk mode setter": "function setRiskMode",
    "risk dashboard route": '"#risk"',
    "ai portfolio dashboard cache": "function fetchAiPortfolioDashboard",
    "market ui module bridge": "window.FinGPTMarketUi",
    "macro ui module bridge": "window.FinGPTMacroUi",
    "forecast ui module bridge": "window.FinGPTForecastUi",
    "forecast visualization overview": "forecast-viz-overview",
    "forecast visualization chart sections": "function renderForecastVizSection",
    "forecast visualization chart shell": "function renderForecastChartCard",
    "forecast visualization axis note": "forecast-axis-note",
    "forecast visualization actual predicted axis": "X축은 모델이 예측한 forward return",
    "forecast universe endpoint": 'forecastUniverseRun: "/api/v1/forecast/universe/run"',
    "forecast universe request": "function forecastUniverseRequestFromControls",
    "forecast universe renderer": "function renderForecastUniverseResult",
    "forecast universe runner": "async function runForecastUniverse",
    "forecast universe styles": "forecast-universe-table",
    "quant ui module bridge": "window.FinGPTQuantUi",
    "ai portfolio ui module bridge": "window.FinGPTAiPortfolioUi",
    "quantamental ui module bridge": "window.FinGPTQuantamentalUi",
    "quantamental api": "quantamentalAnalysis",
    "quantamental ai model options": "function renderQuantamentalAiModelOptions",
    "quantamental ai request options": "function quantamentalAiRequestOptions",
    "quantamental compare api": "quantamentalCompare",
    "quantamental top signal screen api": "quantamentalTopSignals",
    "quantamental score screen api": "quantamentalScoreScreen",
    "quantamental score screen score key": "score_key",
    "quantamental score screen liquidity stability": "liquidity_stability",
    "quantamental score screen trend efficiency": "trend_efficiency",
    "quantamental score screen market resilience": "market_resilience",
    "quantamental score screen tail risk momentum": "tail_risk_momentum",
    "quantamental score screen accumulation quality": "accumulation_quality",
    "quantamental score screen gap risk stability": "gap_risk_stability",
    "quantamental score screen range discipline": "range_discipline",
    "quantamental score screen volatility compression": "volatility_compression",
    "quantamental compare server watchlist api": "quantamentalCompareWatchlists",
    "quantamental snapshot export api": "quantamentalSnapshotExport",
    "quantamental snapshot diff api": "quantamentalSnapshotDiff",
    "quantamental snapshot retention api": "quantamentalSnapshotRetention",
    "output language storage": "fingpt.outputLanguage.v1",
    "output language request field": "output_language: selectedOutputLanguage()",
    "ui language applier": "function applyUiLanguage",
    "ui language binder": "function bindLanguageToggle",
    "quantamental loader": "function loadQuantamental",
    "quantamental runner": "function runQuantamentalAnalysis",
    "quantamental compare runner": "function runQuantamentalCompare",
    "quantamental compare watchlist persistence": "function saveQuantamentalCompareWatchlist",
    "quantamental compare watchlist loader": "function loadQuantamentalCompareWatchlists",
    "quantamental compare csv exporter": "function exportQuantamentalCompareCsv",
    "quantamental screen loader": "function loadQuantamentalScreen",
    "quantamental score screen runner": "function runQuantamentalScoreScreen",
    "quantamental snapshot action exporter": "function exportQuantamentalSnapshot",
    "data auto refresh status api": "dataAutoRefreshStatus: \"/api/v1/data/auto-refresh/status\"",
    "data auto refresh run api": "dataAutoRefreshRun: \"/api/v1/data/auto-refresh/run\"",
    "data auto refresh renderer": "function renderDataAutoRefreshStatus",
    "data auto refresh runner": "async function refreshAllDataNow",
    "quality portal cards": "const QUALITY_PORTAL_CARDS",
    "quality portal mover": "function moveOperationalQualityCardsToQualityPanel",
    "quant model profile loader": "function loadQuantModelProfiles",
    "quality portal forecast": "[\"forecastJobsSurface\", \"qualityOpsForecast\"]",
    "quality portal ai portfolio": "[\"aiPortfolioOperationsSurface\", \"qualityOpsAiPortfolio\"]",
}


REQUIRED_QUANTAMENTAL_MODULE_MARKERS: dict[str, str] = {
    "quantamental quant algorithm summary": "quantamental-quant-algorithm",
    "quantamental quality adjusted momentum algorithm": "quality_adjusted_momentum_v1",
    "quantamental volatility adjusted breakout summary": "quantamental-volatility-breakout-algorithm",
    "quantamental volatility adjusted breakout algorithm": "volatility_adjusted_breakout_v1",
    "quantamental drawdown resilience summary": "quantamental-drawdown-resilience-algorithm",
    "quantamental drawdown resilience algorithm": "drawdown_recovery_resilience_v1",
    "quantamental liquidity stability summary": "quantamental-liquidity-stability-algorithm",
    "quantamental liquidity stability algorithm": "liquidity_participation_stability_v1",
    "quantamental trend efficiency summary": "quantamental-trend-efficiency-algorithm",
    "quantamental trend efficiency algorithm": "trend_efficiency_stability_v1",
    "quantamental market resilience summary": "quantamental-market-resilience-algorithm",
    "quantamental market resilience algorithm": "market_relative_resilience_v1",
    "quantamental tail risk momentum summary": "quantamental-tail-risk-momentum-algorithm",
    "quantamental tail risk momentum algorithm": "tail_risk_adjusted_momentum_v1",
    "quantamental accumulation quality summary": "quantamental-accumulation-quality-algorithm",
    "quantamental accumulation quality algorithm": "volume_accumulation_quality_v1",
    "quantamental gap risk stability summary": "quantamental-gap-risk-stability-algorithm",
    "quantamental gap risk stability algorithm": "gap_risk_stability_v1",
    "quantamental range discipline summary": "quantamental-range-discipline-algorithm",
    "quantamental range discipline algorithm": "range_discipline_v1",
    "quantamental volatility compression summary": "quantamental-volatility-compression-algorithm",
    "quantamental volatility compression algorithm": "volatility_compression_readiness_v1",
    "quantamental decision memo": "function quantamentalDecisionMemo",
    "quantamental decision memo testid": "quantamental-decision-memo",
}


def _matching_lines(text: str, pattern: re.Pattern[str]) -> list[dict[str, Any]]:
    return [
        {"line": line_no, "text": line.strip()[:240]}
        for line_no, line in enumerate(text.splitlines(), start=1)
        if pattern.search(line)
    ]


def run_check() -> dict[str, Any]:
    with TestClient(api_server.app) as client:
        ui_response = client.get("/ui/")
        ui_quantamental_response = client.get("/ui/quantamental")
        ui_missing_asset_response = client.get("/ui/not-found-bundle.js")
        health_response = client.get("/api/v1/health")

    html = ui_response.text
    app_js_path = Path(__file__).resolve().parents[1] / "app" / "web" / "app.js"
    app_js = app_js_path.read_text(encoding="utf-8")
    quantamental_js_path = Path(__file__).resolve().parents[1] / "app" / "web" / "modules" / "quantamental-ui.js"
    quantamental_js = quantamental_js_path.read_text(encoding="utf-8")
    missing = [name for name, marker in REQUIRED_UI_MARKERS.items() if marker not in html]
    missing_js = [name for name, marker in REQUIRED_APP_JS_MARKERS.items() if marker not in app_js]
    missing_quantamental_js = [
        name for name, marker in REQUIRED_QUANTAMENTAL_MODULE_MARKERS.items() if marker not in quantamental_js
    ]
    mojibake_lines = _matching_lines(html, HTML_MOJIBAKE_RE)
    placeholder_lines = _matching_lines(html, HTML_PLACEHOLDER_RE)
    passed = (
        ui_response.status_code == 200
        and ui_quantamental_response.status_code == 200
        and ui_missing_asset_response.status_code == 404
        and health_response.status_code == 200
        and not missing
        and not missing_js
        and not missing_quantamental_js
        and not mojibake_lines
        and not placeholder_lines
    )
    return {
        "status": "passed" if passed else "failed",
        "ui_status": ui_response.status_code,
        "ui_quantamental_route_status": ui_quantamental_response.status_code,
        "ui_missing_asset_status": ui_missing_asset_response.status_code,
        "health_status": health_response.status_code,
        "missing_markers": missing,
        "missing_js_markers": missing_js,
        "missing_quantamental_js_markers": missing_quantamental_js,
        "mojibake_lines": mojibake_lines,
        "placeholder_lines": placeholder_lines,
        "checked_markers": sorted(REQUIRED_UI_MARKERS),
        "checked_js_markers": sorted(REQUIRED_APP_JS_MARKERS),
        "checked_quantamental_js_markers": sorted(REQUIRED_QUANTAMENTAL_MODULE_MARKERS),
        "html_bytes": len(html.encode("utf-8", errors="ignore")),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Check the FinGPT UI/API contract without a browser.")
    parser.add_argument("--output", default="reports/ui_contract_latest.json")
    args = parser.parse_args()

    report = run_check()
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report["status"] == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
