from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

from fastapi.testclient import TestClient

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.api import server as api_server


HTML_MOJIBAKE_RE = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff\ufffd]")
HTML_PLACEHOLDER_RE = re.compile(r"\?{2,}")

REQUIRED_UI_MARKERS: dict[str, str] = {
    "analysis form": 'id="analysisForm"',
    "ticker input": 'id="ticker"',
    "ticker search picker": 'id="tickerSearchOpen"',
    "question textarea": 'id="question"',
    "language toggle": 'id="languageToggle"',
    "language toggle korean": 'data-language="ko"',
    "language toggle english": 'data-language="en"',
    "result view": 'id="resultView"',
    "home dashboard": 'id="emptyState"',
    "dashboard tabs": 'id="homeDashboardTabs"',
    "dashboard decision context strip": 'id="dashboardContextStrip"',
    "global quality summary": 'id="globalQualitySummary"',
    "global quality observations": 'data-summary-field="observations"',
    "global quality missing": 'data-summary-field="missing"',
    "global quality ai snapshot": 'data-summary-field="ai-snapshot"',
    "global quality context": 'id="qualityContextSummary"',
    "global quality context source": 'data-quality-detail="source"',
    "global quality context cache": 'data-quality-detail="cache"',
    "global quality context range support": 'data-quality-detail="range-support"',
    "global dashboard range controls": 'id="dashboardRangeControls"',
    "global dashboard range select": 'id="dashboardRangeSelect"',
    "global dashboard range start": 'id="dashboardRangeStart"',
    "global dashboard range end": 'id="dashboardRangeEnd"',
    "quantamental ai model selector": 'id="quantamentalAiModel"',
    "quantamental ai model status": 'id="quantamentalAiModelStatus"',
    "quantamental ai model contract": 'data-testid="quantamental-ai-model-control"',
    "market dashboard tab": 'id="marketDashboardTab"',
    "market dashboard tab testid": 'data-testid="market-dashboard-tab"',
    "macro dashboard tab": 'id="macroDashboardTab"',
    "macro dashboard tab testid": 'data-testid="macro-dashboard-tab"',
    "quant lab tab": 'id="quantLabTab"',
    "quant lab tab testid": 'data-testid="quant-lab-tab"',
    "quantamental tab": 'id="quantamentalTab"',
    "quantamental tab testid": 'data-testid="quantamental-tab"',
    "ml forecast tab": 'id="mlForecastTab"',
    "ml forecast tab testid": 'data-testid="ml-forecast-tab"',
    "ai portfolio tab": 'id="aiPortfolioTab"',
    "ai portfolio tab testid": 'data-testid="ai-portfolio-tab"',
    "run history": 'id="historyList"',
    "market snapshot": 'id="homeMarketList"',
    "market overview meta": 'id="marketOverviewMeta"',
    "market tape": 'id="marketTapeSurface"',
    "market signals": 'id="marketSignalSurface"',
    "cross asset symbols": 'id="crossAssetSymbols"',
    "cross asset analysis": 'id="crossAssetAnalysisSurface"',
    "cross asset run": 'data-testid="cross-asset-run"',
    "home news": 'id="homeNewsList"',
    "focused news": 'id="homeNewsFocusedList"',
    "news search run": 'data-testid="market-news-search-run"',
    "tradingview chart": 'id="tvOverviewWidget"',
    "market chart source": 'id="tvChartSource"',
    "tradingview chart symbol": 'id="tvChartSymbol"',
    "tradingview chart interval": 'id="tvChartInterval"',
    "tradingview chart compare": 'id="tvChartCompare"',
    "tradingview chart apply": 'data-testid="tradingview-chart-apply"',
    "intraday heatmap": 'id="homeHeatmap"',
    "intraday heatmap refresh": 'id="homeHeatmapRefresh"',
    "intraday heatmap refresh testid": 'data-testid="market-heatmap-refresh"',
    "data health": 'id="homeDataHealth"',
    "data health refresh": 'id="dataHealthRefresh"',
    "data health refresh testid": 'data-testid="data-health-refresh"',
    "macro surface": 'id="macroSurface"',
    "macro refresh": 'id="macroRefresh"',
    "macro refresh testid": 'data-testid="macro-refresh"',
    "macro brief generate": 'id="macroBriefGenerate"',
    "macro brief generate testid": 'data-testid="macro-brief-generate"',
    "macro report export": 'id="macroReportExport"',
    "macro report export testid": 'data-testid="macro-report-export"',
    "macro load status": 'id="macroLoadStatus"',
    "macro overview": 'id="macroOverviewSurface"',
    "macro coverage": 'id="macroCoverageSurface"',
    "macro provider health": 'id="macroProviderHealthSurface"',
    "macro series search input": 'id="macroSeriesSearchInput"',
    "macro series search action": 'id="macroSeriesSearchRun"',
    "macro series search action testid": 'data-testid="macro-series-search-run"',
    "macro series search results": 'id="macroSeriesSearchResults"',
    "macro series detail": 'id="macroSeriesDetailSurface"',
    "macro provider filter": 'id="macroProviderFilter"',
    "macro category filter": 'id="macroCategoryFilter"',
    "macro compare": 'id="macroCompareSurface"',
    "macro indicators": 'id="macroIndicatorTable"',
    "macro chart surface": 'id="macroChartSurface"',
    "macro interest rates": 'id="macroInterestRatesSurface"',
    "macro inflation": 'id="macroInflationSurface"',
    "macro growth labor": 'id="macroGrowthLaborSurface"',
    "macro housing consumer": 'id="macroHousingConsumerSurface"',
    "macro yield curve": 'id="macroYieldCurveSurface"',
    "macro liquidity credit": 'id="macroLiquidityCreditSurface"',
    "macro financial conditions": 'id="macroFinancialConditionsSurface"',
    "macro fx dollar": 'id="macroFxDollarSurface"',
    "macro commodities": 'id="macroCommoditiesSurface"',
    "macro regime": 'id="macroRegimeSurface"',
    "macro asset impact": 'id="macroAssetImpactSurface"',
    "macro scenario": 'id="macroScenarioSurface"',
    "macro scenario action": 'data-action="macro-scenario"',
    "macro research preview": 'id="macroResearchPreviewSurface"',
    "macro research ticker": 'id="macroResearchTicker"',
    "macro research preview action": 'id="macroResearchPreviewRun"',
    "macro research preview action testid": 'data-testid="macro-research-preview-run"',
    "macro research preview result": 'id="macroResearchPreviewResult"',
    "macro portfolio hints": 'id="macroPortfolioHintsSurface"',
    "macro brief": 'id="macroBriefSurface"',
    "macro data quality": 'id="macroDataQualitySurface"',
    "asset detail": 'id="assetDetailSurface"',
    "asset detail ticker picker": 'id="assetDetailTickerOpen"',
    "asset detail range": 'id="assetDetailRange"',
    "asset detail start date": 'id="assetDetailStartDate"',
    "asset detail end date": 'id="assetDetailEndDate"',
    "asset detail view": 'id="assetDetailView"',
    "asset detail benchmark": 'id="assetDetailBenchmark"',
    "asset detail benchmark picker": 'id="assetDetailBenchmarkOpen"',
    "asset detail benchmark compare": 'id="assetDetailBenchmarkCompare"',
    "quant feature preview": 'id="quantFeatureSurface"',
    "quant feature preview action": 'id="quantFeatureRun"',
    "quant feature preview action testid": 'data-testid="quant-feature-run"',
    "quant signal matrix": 'id="quantSignalSurface"',
    "quant signal matrix action": 'id="quantSignalRun"',
    "quant signal matrix action testid": 'data-testid="quant-signal-run"',
    "strategy governance": 'id="quantStrategySurface"',
    "strategy refresh": 'id="quantStrategyRefresh"',
    "strategy refresh testid": 'data-testid="quant-strategy-refresh"',
    "strategy new draft": 'id="quantStrategyNewDraft"',
    "strategy new draft testid": 'data-testid="quant-strategy-new-draft"',
    "strategy prompt": 'id="strategyPromptInput"',
    "strategy generate": 'id="quantStrategyGenerate"',
    "strategy generate testid": 'data-testid="quant-strategy-generate"',
    "strategy editor": 'id="strategyDefinitionJson"',
    "strategy review": 'id="strategyPromptReviewSurface"',
    "strategy editor note": 'class="strategy-editor-note"',
    "strategy dry run": 'id="quantStrategyDryRun"',
    "strategy dry run testid": 'data-testid="quant-strategy-dry-run"',
    "strategy save": 'id="quantStrategySave"',
    "strategy save testid": 'data-testid="quant-strategy-save"',
    "strategy delete": 'id="quantStrategyDelete"',
    "strategy delete testid": 'data-testid="quant-strategy-delete"',
    "backtest": 'id="backtestSurface"',
    "backtest run": 'id="backtestRun"',
    "backtest run testid": 'data-testid="quant-backtest-run"',
    "backtest universe picker": 'id="backtestUniverseOpen"',
    "backtest universe chips": 'id="backtestUniverseChips"',
    "backtest strategy registry": 'id="backtestStrategyRegistry"',
    "backtest risk adjusted momentum option": 'value="risk_adjusted_momentum"',
    "backtest benchmark": 'id="backtestBenchmark"',
    "backtest benchmark picker": 'id="backtestBenchmarkOpen"',
    "backtest benchmark compare": 'id="backtestBenchmarkCompare"',
    "symbol picker modal": 'id="symbolPickerModal"',
    "symbol picker title": 'id="symbolPickerTitle"',
    "symbol picker description": 'id="symbolPickerDescription"',
    "symbol picker summary": 'id="symbolPickerSummary"',
    "symbol picker add filtered": 'id="symbolPickerAddFiltered"',
    "symbol picker remove filtered": 'id="symbolPickerRemoveFiltered"',
    "freshness profile": 'id="backtestFreshnessProfile"',
    "strict freshness toggle": 'id="backtestRequireFresh"',
    "research score toggle": 'id="backtestUseResearchScore"',
    "quant run history": 'id="quantRunHistorySurface"',
    "quant run history refresh": 'id="quantRunHistoryRefresh"',
    "quant run history refresh testid": 'data-testid="quant-run-history-refresh"',
    "quant export storage report": 'id="quantExportStorageReport"',
    "quant export storage report testid": 'data-testid="quant-export-storage-report"',
    "quant cross-run cleanup preview": 'id="quantCrossRunCleanupPreview"',
    "quant cross-run cleanup preview testid": 'data-testid="quant-cross-run-cleanup-preview"',
    "quantamental surface": 'id="quantamentalSurface"',
    "quantamental ticker": 'id="quantamentalTicker"',
    "quantamental ticker picker": 'id="quantamentalTickerOpen"',
    "quantamental market": 'id="quantamentalMarket"',
    "quantamental period": 'id="quantamentalPeriod"',
    "quantamental years": 'id="quantamentalYears"',
    "quantamental lookback": 'id="quantamentalLookback"',
    "quantamental style": 'id="quantamentalStyle"',
    "quantamental analyze": 'id="quantamentalAnalyze"',
    "quantamental analyze testid": 'data-testid="quantamental-analyze"',
    "quantamental company": 'id="quantamentalCompanySurface"',
    "quantamental signal": 'id="quantamentalSignalSurface"',
    "quantamental score": 'id="quantamentalScoreSurface"',
    "quantamental factors": 'id="quantamentalFactorSurface"',
    "quantamental main": 'id="quantamentalMainSurface"',
    "quantamental ai report": 'id="quantamentalAiRefresh"',
    "quantamental ai report testid": 'data-testid="quantamental-ai-report"',
    "quantamental data quality": 'id="quantamentalDataQualitySurface"',
    "ml forecast surface": 'id="mlForecastSurface"',
    "ml forecast ticker": 'id="forecastTicker"',
    "ml forecast ticker picker": 'id="forecastTickerOpen"',
    "ml forecast benchmark": 'id="forecastBenchmark"',
    "ml forecast benchmark picker": 'id="forecastBenchmarkOpen"',
    "ml forecast horizon": 'id="forecastHorizon"',
    "ml forecast target": 'id="forecastTargetType"',
    "ml forecast model": 'id="forecastModel"',
    "ml forecast validation": 'id="forecastValidation"',
    "ml forecast preview action": 'id="forecastPreviewDataset"',
    "ml forecast preview testid": 'data-testid="ml-forecast-preview"',
    "ml forecast hydrate action": 'id="forecastHydrateDataset"',
    "ml forecast hydrate testid": 'data-testid="ml-forecast-hydrate"',
    "ml forecast feature action": 'id="forecastBuildFeatures"',
    "ml forecast feature testid": 'data-testid="ml-forecast-features"',
    "ml forecast train action": 'id="forecastRunTrain"',
    "ml forecast train testid": 'data-testid="ml-forecast-train"',
    "ml forecast ai action": 'id="forecastGenerateAi"',
    "ml forecast ai testid": 'data-testid="ml-forecast-ai"',
    "ml forecast provider ai action": 'id="forecastGenerateProviderAi"',
    "ml forecast provider ai testid": 'data-testid="ml-forecast-provider-ai"',
    "ml forecast dataset": 'id="forecastDatasetSurface"',
    "ml forecast features": 'id="forecastFeatureSurface"',
    "ml forecast leakage": 'id="forecastLeakageSurface"',
    "ml forecast result": 'id="forecastResultSurface"',
    "ml forecast signal": 'id="forecastSignalSurface"',
    "ml forecast signal quality": 'id="forecastSignalQualitySurface"',
    "ml forecast visualization": 'id="forecastVizSurface"',
    "ml forecast backtest": 'id="forecastBacktestSurface"',
    "ml forecast evaluation": 'id="forecastEvaluationSurface"',
    "ml forecast explain": 'id="forecastExplainSurface"',
    "ml forecast ai surface": 'id="forecastAiSurface"',
    "ml forecast ai provider check": 'id="forecastAiProviderCheck"',
    "ml forecast ai provider surface": 'id="forecastAiProviderSurface"',
    "ml forecast drift refresh": 'id="forecastDriftRefresh"',
    "ml forecast drift surface": 'id="forecastDriftSurface"',
    "ml forecast model comparison refresh": 'id="forecastModelComparisonRefresh"',
    "ml forecast model comparison surface": 'id="forecastModelComparisonSurface"',
    "ml forecast history": 'id="forecastHistorySurface"',
    "ml forecast registry": 'id="forecastRegistrySurface"',
    "portfolio optimizer": 'id="portfolioSurface"',
    "portfolio universe picker": 'id="portfolioUniverseOpen"',
    "portfolio universe chips": 'id="portfolioUniverseChips"',
    "portfolio sync backtest": 'id="portfolioSyncBacktest"',
    "portfolio sync backtest testid": 'data-testid="portfolio-sync-backtest"',
    "portfolio optimize action": 'id="portfolioOptimize"',
    "portfolio optimize action testid": 'data-testid="portfolio-optimize"',
    "portfolio benchmark": 'id="portfolioBenchmark"',
    "portfolio benchmark picker": 'id="portfolioBenchmarkOpen"',
    "portfolio covariance method": 'id="portfolioCovarianceMethod"',
    "ai portfolio surface": 'id="aiPortfolioSurface"',
    "ai portfolio investment types": 'id="aiPortfolioInvestmentTypes"',
    "ai portfolio universe preset": 'id="aiPortfolioUniverse"',
    "ai portfolio custom universe": 'id="aiPortfolioCustomUniverse"',
    "ai portfolio custom universe picker": 'id="aiPortfolioCustomUniverseOpen"',
    "ai portfolio custom universe chips": 'id="aiPortfolioCustomUniverseChips"',
    "ai portfolio universe status": 'id="aiPortfolioUniverseStatus"',
    "ai portfolio ops": 'id="aiPortfolioOpsSurface"',
    "ai portfolio ops refresh": 'id="aiPortfolioOpsRefresh"',
    "quantamental composite": 'id="quantamentalScoreSurface"',
    "quantamental factor": 'id="quantamentalFactorSurface"',
    "quantamental ai action": 'id="quantamentalAiRefresh"',
    "quantamental ai testid": 'data-testid="quantamental-ai-report"',
    "quantamental quality": 'id="quantamentalDataQualitySurface"',
    "quantamental compare tickers": 'id="quantamentalCompareTickers"',
    "quantamental compare action": 'id="quantamentalCompareRun"',
    "quantamental compare testid": 'data-testid="quantamental-compare-run"',
    "quantamental compare surface": 'id="quantamentalCompareSurface"',
    "quantamental expand peers": 'id="quantamentalExpandPeers"',
    "quantamental peer limit": 'id="quantamentalPeerLimit"',
    "quantamental compare watchlist name": 'id="quantamentalWatchlistName"',
    "quantamental compare watchlist select": 'id="quantamentalWatchlistSelect"',
    "quantamental compare watchlist save": 'data-testid="quantamental-watchlist-save"',
    "quantamental compare watchlist load": 'data-testid="quantamental-watchlist-load"',
    "quantamental compare csv": 'data-testid="quantamental-compare-csv"',
    "quantamental screen action": 'id="quantamentalScreenRun"',
    "quantamental screen action testid": 'data-testid="quantamental-screen-run"',
    "quantamental screen status": 'id="quantamentalScreenStatus"',
    "quantamental screen surface": 'id="quantamentalScreenSurface"',
    "quantamental score screen threshold": 'id="quantamentalScoreThreshold"',
    "quantamental score screen metric": 'id="quantamentalScoreMetric"',
    "quantamental score screen limit": 'id="quantamentalScoreScreenLimit"',
    "quantamental score screen action": 'id="quantamentalScoreScreenRun"',
    "quantamental score screen action testid": 'data-testid="quantamental-score-screen-run"',
    "quantamental score screen status": 'id="quantamentalScoreScreenStatus"',
    "quantamental score screen surface": 'id="quantamentalScoreScreenSurface"',
    "market ui module": 'modules/market-ui.js?v=20260514-domain-modules',
    "macro ui module": 'modules/macro-ui.js?v=20260514-domain-modules',
    "forecast ui module": 'modules/forecast-ui.js?v=20260514-domain-modules',
    "quant ui module": 'modules/quant-ui.js?v=20260514-domain-modules',
    "ai portfolio ui module": 'modules/ai-portfolio-ui.js?v=20260514-domain-modules',
    "quantamental ui module": 'modules/quantamental-ui.js?v=20260519-quantamental-v16',
    "ai portfolio operation hydrate": 'id="aiPortfolioHydrateData"',
    "ai portfolio operation retry": 'id="aiPortfolioRetryMissing"',
    "ai portfolio snapshot job": 'id="aiPortfolioSnapshotJob"',
    "ai portfolio sec refresh": 'id="aiPortfolioSecRefresh"',
    "ai portfolio policy list": 'id="aiPortfolioPolicyListSurface"',
    "ai portfolio recommendation diff": 'id="aiPortfolioRecommendationDiffSurface"',
    "ai portfolio operations history": 'id="aiPortfolioOperationsSurface"',
    "ai portfolio policy form": 'id="aiPortfolioPolicyForm"',
    "ai portfolio benchmark picker": 'id="aiPortfolioBenchmarkOpen"',
    "ai portfolio generate": 'id="aiPortfolioGenerate"',
    "ai portfolio recommendation": 'id="aiPortfolioRecommendationSurface"',
    "ai portfolio performance": 'id="aiPortfolioPerformanceSurface"',
    "ai portfolio compliance": 'id="aiPortfolioComplianceSurface"',
    "ai portfolio rebalance": 'id="aiPortfolioRebalanceSurface"',
    "ai portfolio reports": 'id="aiPortfolioReportsSurface"',
    "ai portfolio history": 'id="aiPortfolioHistorySurface"',
}

REQUIRED_APP_JS_MARKERS: dict[str, str] = {
    "all default panel views": "DEFAULT_DASHBOARD_PANEL_VIEWS",
    "all default panel version": "DASHBOARD_PANEL_LAYOUT_VERSION",
    "global range storage": "fingpt.dashboardRange.v1",
    "global range setter": "function setGlobalRange",
    "global range date order guard": "function normalizeCustomGlobalDateOrder",
    "global range validation copy": "function globalRangeValidationMessage",
    "global range support summary": "function globalRangeSupportSummary",
    "global quality summary": "function updateGlobalQualitySummary",
    "global quality range pending": "function markGlobalQualityRangePending",
    "global quality context summary": "function renderGlobalQualityContextSummary",
    "global quality missing summary": "function displayMissingSummary",
    "global quality ai basis label": "AI 기준:",
    "dashboard decision cards api": "dashboardDecisionCards",
    "dashboard decision cards loader": "function loadDashboardDecisionCards",
    "dashboard intraday chart api": "dashboardIntraday",
    "internal chart payload loader": "function fetchInternalChartPayload",
    "internal chart intraday intervals": "TV_INTERNAL_INTRADAY_INTERVALS",
    "macro default series detail loader": "function loadMacroDefaultSeriesDetail",
    "macro dashboard api": "macroDashboard",
    "macro provider health api": "macroProviderHealth",
    "macro scenario api": "macroScenario",
    "macro research context api": "macroResearchContext",
    "macro timeout fetch": "macroFetchJsonWithTimeout",
    "macro load status renderer": "function renderMacroLoadStatus",
    "macro panel failure renderer": "function renderMacroPanelFailure",
    "macro action pane starter renderer": "function renderMacroActionPaneStarters",
    "macro refresh preserves dashboard": "\uae30\uc874 \ub300\uc2dc\ubcf4\ub4dc \ud654\uba74\uc744 \uc720\uc9c0",
    "macro provider health renderer": "function renderMacroProviderHealth",
    "macro scenario runner": "function runMacroScenario",
    "macro research preview runner": "function runMacroResearchPreview",
    "ai portfolio dashboard cache": "function fetchAiPortfolioDashboard",
    "market ui module bridge": "window.FinGPTMarketUi",
    "macro ui module bridge": "window.FinGPTMacroUi",
    "forecast ui module bridge": "window.FinGPTForecastUi",
    "quant ui module bridge": "window.FinGPTQuantUi",
    "ai portfolio ui module bridge": "window.FinGPTAiPortfolioUi",
    "quantamental ui module bridge": "window.FinGPTQuantamentalUi",
    "quantamental api": "quantamentalAnalysis",
    "quantamental ai model options": "function renderQuantamentalAiModelOptions",
    "quantamental ai request options": "function quantamentalAiRequestOptions",
    "quantamental compare api": "quantamentalCompare",
    "quantamental top signal screen api": "quantamentalTopSignals",
    "quantamental score screen api": "quantamentalScoreScreen",
    "quantamental score screen score key": "score_key",
    "quantamental score screen liquidity stability": "liquidity_stability",
    "quantamental score screen trend efficiency": "trend_efficiency",
    "quantamental compare server watchlist api": "quantamentalCompareWatchlists",
    "quantamental snapshot export api": "quantamentalSnapshotExport",
    "quantamental snapshot diff api": "quantamentalSnapshotDiff",
    "quantamental snapshot retention api": "quantamentalSnapshotRetention",
    "output language storage": "fingpt.outputLanguage.v1",
    "output language request field": "output_language: selectedOutputLanguage()",
    "ui language applier": "function applyUiLanguage",
    "ui language binder": "function bindLanguageToggle",
    "quantamental loader": "function loadQuantamental",
    "quantamental runner": "function runQuantamentalAnalysis",
    "quantamental compare runner": "function runQuantamentalCompare",
    "quantamental compare watchlist persistence": "function saveQuantamentalCompareWatchlist",
    "quantamental compare watchlist loader": "function loadQuantamentalCompareWatchlists",
    "quantamental compare csv exporter": "function exportQuantamentalCompareCsv",
    "quantamental screen loader": "function loadQuantamentalScreen",
    "quantamental score screen runner": "function runQuantamentalScoreScreen",
    "quantamental snapshot action exporter": "function exportQuantamentalSnapshot",
}


REQUIRED_QUANTAMENTAL_MODULE_MARKERS: dict[str, str] = {
    "quantamental quant algorithm summary": "quantamental-quant-algorithm",
    "quantamental quality adjusted momentum algorithm": "quality_adjusted_momentum_v1",
    "quantamental volatility adjusted breakout summary": "quantamental-volatility-breakout-algorithm",
    "quantamental volatility adjusted breakout algorithm": "volatility_adjusted_breakout_v1",
    "quantamental drawdown resilience summary": "quantamental-drawdown-resilience-algorithm",
    "quantamental drawdown resilience algorithm": "drawdown_recovery_resilience_v1",
    "quantamental liquidity stability summary": "quantamental-liquidity-stability-algorithm",
    "quantamental liquidity stability algorithm": "liquidity_participation_stability_v1",
    "quantamental trend efficiency summary": "quantamental-trend-efficiency-algorithm",
    "quantamental trend efficiency algorithm": "trend_efficiency_stability_v1",
}


def _matching_lines(text: str, pattern: re.Pattern[str]) -> list[dict[str, Any]]:
    return [
        {"line": line_no, "text": line.strip()[:240]}
        for line_no, line in enumerate(text.splitlines(), start=1)
        if pattern.search(line)
    ]


def run_check() -> dict[str, Any]:
    with TestClient(api_server.app) as client:
        ui_response = client.get("/ui/")
        ui_quantamental_response = client.get("/ui/quantamental")
        ui_missing_asset_response = client.get("/ui/not-found-bundle.js")
        health_response = client.get("/api/v1/health")

    html = ui_response.text
    app_js_path = Path(__file__).resolve().parents[1] / "app" / "web" / "app.js"
    app_js = app_js_path.read_text(encoding="utf-8")
    quantamental_js_path = Path(__file__).resolve().parents[1] / "app" / "web" / "modules" / "quantamental-ui.js"
    quantamental_js = quantamental_js_path.read_text(encoding="utf-8")
    missing = [name for name, marker in REQUIRED_UI_MARKERS.items() if marker not in html]
    missing_js = [name for name, marker in REQUIRED_APP_JS_MARKERS.items() if marker not in app_js]
    missing_quantamental_js = [
        name for name, marker in REQUIRED_QUANTAMENTAL_MODULE_MARKERS.items() if marker not in quantamental_js
    ]
    mojibake_lines = _matching_lines(html, HTML_MOJIBAKE_RE)
    placeholder_lines = _matching_lines(html, HTML_PLACEHOLDER_RE)
    passed = (
        ui_response.status_code == 200
        and ui_quantamental_response.status_code == 200
        and ui_missing_asset_response.status_code == 404
        and health_response.status_code == 200
        and not missing
        and not missing_js
        and not missing_quantamental_js
        and not mojibake_lines
        and not placeholder_lines
    )
    return {
        "status": "passed" if passed else "failed",
        "ui_status": ui_response.status_code,
        "ui_quantamental_route_status": ui_quantamental_response.status_code,
        "ui_missing_asset_status": ui_missing_asset_response.status_code,
        "health_status": health_response.status_code,
        "missing_markers": missing,
        "missing_js_markers": missing_js,
        "missing_quantamental_js_markers": missing_quantamental_js,
        "mojibake_lines": mojibake_lines,
        "placeholder_lines": placeholder_lines,
        "checked_markers": sorted(REQUIRED_UI_MARKERS),
        "checked_js_markers": sorted(REQUIRED_APP_JS_MARKERS),
        "checked_quantamental_js_markers": sorted(REQUIRED_QUANTAMENTAL_MODULE_MARKERS),
        "html_bytes": len(html.encode("utf-8", errors="ignore")),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Check the FinGPT UI/API contract without a browser.")
    parser.add_argument("--output", default="reports/ui_contract_latest.json")
    args = parser.parse_args()

    report = run_check()
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report["status"] == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
